### PR TITLE
Create Guess-the-number-game.py

### PR DESCRIPTION
**Pull request by arijitparia2002**
I have added a python code for a cool game called "Guess the number".

### CODE REVIEW

**Comment by arijitparia2002** [comment]
Please accept the pull request as it will be a good addition to this repository. And it is my first time contribution to opensource.

**Comment by arijitparia2002** [comment]
Please accept the PR , as the code i have added will be a good addition to this repository. Thank you!

**Comment by arijitparia2002** [comment]
Please accept the PR , as the code i have added will be a good addition to this repository. Thank you!

**Comment by arijitparia2002** [comment]
Please accept the PR , as the code i have added will be a good addition to this repository. Thank you! And this is my first time contribution to HacktoberFest.

**Comment by Arunim313** [comment]
Already present, please upload another.

**Pull request merged**
